name: build and deploy spfx

on:
  workflow_call:
    inputs:
      include_tests:
        description: 'Indicates whether build job has to run tests or not'
        default: false
        required: false
        type: boolean
      site_url_prd:
        description: 'SharePoint PRD site URL'
        required: true
        type: string
      deploy_uat:
        description: 'States whether the deployment on UAT environment must be done or not'
        default: false
        required: false
        type: boolean
      deploy_prd:
        description: 'States whether the deployment on PRD environment must be done or not'
        default: false
        required: false
        type: boolean

jobs:
  build-spfx:
    uses: michaelmaillot/mwcp22/.github/workflows/jobs/build-spfx.yml@v1
  deploy-spfx-uat:
    if: ${{ inputs.deploy_uat == true }}
    uses: michaelmaillot/mwcp22/.github/workflows/jobs/deploy-spfx-cli-m365.yml@v1
    with:
      site_url_prd: ${{ inputs.site_url_prd }}
  deploy-spfx-prd:
    if: ${{ inputs.deploy_prd == true }}
    uses: michaelmaillot/mwcp22/.github/workflows/jobs/deploy-spfx-cli-m365.yml@v1
    with:
      site_url_prd: ${{ inputs.site_url_prd }}
      