name: main
on:
  push:
    branches: 
      - main
  workflow_dispatch:

jobs:
  build_spfx:
    uses: michaelmaillot/mwcp22/.github/workflows/build-spfx.yml@main
  test:
    needs: build_spfx
    runs-on: ubuntu-latest
    steps:
      - name: GetSharePointPackage
        shell: pwsh
        run: Write-Host "${{ env.SPPKG_FILE }}"
  deploy_spfx_uat:
    needs: build_spfx
    uses: michaelmaillot/mwcp22/.github/workflows/deploy-spfx-cli-m365.yml@main
    with:
      environment_name: UAT
      spfx_package_name: ${{ needs.jobs.build_spfx.outputs.package_name }}
      site_url_prd: https://onepointdev365.sharepoint.com/sites/CommSite
      site_list_prd: Lists/EmployeeOnboarding
    secrets:
      AAD_APP_ID: ${{ secrets.AAD_APP_ID }}
      AAD_APP_PASSWORD: ${{ secrets.AAD_APP_PASSWORD }}
      AAD_APP_ENCODED_CERTIFICATE: ${{ secrets.AAD_APP_ENCODED_CERTIFICATE }}
      AAD_APP_THUMBPRINT: ${{ secrets.AAD_APP_THUMBPRINT }}
      AAD_TENANT_ID: ${{ secrets.AAD_TENANT_ID }}
  deploy_spfx_prd:
    needs: deploy_spfx_uat
    uses: michaelmaillot/mwcp22/.github/workflows/deploy-spfx-cli-m365.yml@main
    with:
      environment_name: PRD
      spfx_package_name: ${{ needs.jobs.build_spfx.outputs.package_name }}
      site_url_prd: https://onepointdev365.sharepoint.com/sites/CommSite
      site_to_remove: "${{ needs.deploy_spfx_uat.outputs.site_bla }}"
    secrets:
      AAD_APP_ID: ${{ secrets.AAD_APP_ID }}
      AAD_APP_PASSWORD: ${{ secrets.AAD_APP_PASSWORD }}
      AAD_APP_ENCODED_CERTIFICATE: ${{ secrets.AAD_APP_ENCODED_CERTIFICATE }}
      AAD_APP_THUMBPRINT: ${{ secrets.AAD_APP_THUMBPRINT }}
      AAD_TENANT_ID: ${{ secrets.AAD_TENANT_ID }}