name: main
on:
  push:
    branches: 
      - main
  workflow_dispatch:

jobs:
  build-spfx:
    uses: michaelmaillot/mwcp22/.github/workflows/build-spfx.yml@main
  deploy-spfx-uat:
    needs: build-spfx
    uses: michaelmaillot/mwcp22/.github/workflows/deploy-spfx-cli-m365.yml@main
    with:
      site_url_prd: https://onepointdev365.sharepoint.com/sites/CommSite
      environment_name: UAT
  deploy-spfx-prd:
    needs: deploy-spfx-uat
    uses: michaelmaillot/mwcp22/.github/workflows/deploy-spfx-cli-m365.yml@main
    with:
      site_url_prd: https://onepointdev365.sharepoint.com/sites/CommSite
      environment_name: PRD